- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Install kubeadm, kubelet, kubectl
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - kubeadm
    - kubelet
    - kubectl

- name: Get the external IP of the machine
      shell: |
        IPADDR=$(curl ifconfig.me && echo "")
        NODENAME=$(hostname -s)
        POD_CIDR="192.168.0.0/16"

- name: Initialize Kubernetes master
  command: kubeadm init --control-plane-endpoint=$IPADDR --apiserver-cert-extra-sans=$IPADDR --pod-network-cidr=$POD_CIDR --node-name=$NODENAME

- name: Create join command file
      ansible.builtin.shell:
        cmd: sudo kubeadm token create --print-join-command > /home/ubuntu/joincommand.sh
      args:
        executable: /bin/bash

- name: Transfer join command file from Master Node to Worker Node1
      ansible.builtin.command: scp -o StrictHostKeyChecking=no -i /home/ubuntu/keypair.pem /home/ubuntu/joincommand.sh ubuntu@{{ hostvars['worker1']['ansible_host'] }}:/home/ubuntu/.

- name: Transfer join command file from Master Node to Worker Node2
      ansible.builtin.command: scp -o StrictHostKeyChecking=no -i /home/ubuntu/keypair.pem /home/ubuntu/joincommand.sh ubuntu@{{ hostvars['worker2']['ansible_host'] }}:/home/ubuntu/.

- name: Set up kubeconfig for the master user
  shell: |
    mkdir -p $HOME/.kube
    cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube/config
